export const arrayOfPreferences = [
    "Amusement parks",
    "Art galleries",
    "Bars",
    "Beaches",
    "Bike rental",
    "Book stores",
    "Botanical gardens",
    "Bowling alleys",
    "Cafes",
    "Comedy clubs",
    "Concerts",
    "Hiking trails",
    "Ice skating rinks",
    "Karaoke",
    "Movie theaters",
    "Pizza",
    "Tennis",
    "Wineries",
];
